### ISSUE TITLE
Betakeys

### ISSUE THREAD

**Issue by NoNamePro0** [SoulGames/TeamPanel#8]
_Management for the Betakeys_

**ToDo:**
- [x] Betakeys List _([Commit](https://github.com/SoulGames/TeamPanel/commit/911c3ad35852191aafe4d970148a42a0b2d62242))_
- [x] Betakeys Creation _([Commit](https://github.com/SoulGames/TeamPanel/commit/0ff3cf19e5a6c02ef117247632d864a8a3f206bd))_
- [x] Betakeys Deletion _([Commit](https://github.com/SoulGames/TeamPanel/commit/0db3a72425022fa5477e83633400fb2bbddc13d5))_
- [x] Navbar _([Commit](https://github.com/SoulGames/TeamPanel/commit/911c3ad35852191aafe4d970148a42a0b2d62242))_

_Development Branch: **[`dev/betakeys`](https://github.com/SoulGames/TeamPanel/tree/dev/betakeys)**_
